[package]
name = "tool"
version = "0.1.0"
authors = ["Luke Hsiao <luke@hsiao.dev>"]
edition = "2021"
description = "A simple CLI tool my personal helper scripts."
repository = "https://github.com/lukehsiao/tool"
readme = "README.md"
license = "Apache-2.0 OR MIT"
categories = ["command-line-utilities"]
publish = false
rust-version = "1.64"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive", "env", "wrap_help", "cargo"] }
clap-verbosity-flag = "2.0.0"
duct = "0.13.6"
env_logger = "0.10.0"
log = "0.4.17"
once_cell = "1.16.0"
regex = "1.7.0"
semver = "1.0.16"
tempfile = "3.3.0"
tera = "1.17.1"
xshell = "0.2.3"
