[package]
name = "tool"
version = "0.0.1"
authors = ["Luke Hsiao <luke@hsiao.dev>"]
edition = "2021"
description = "A simple CLI tool my personal helper scripts."
repository = "https://github.com/lukehsiao/tool"
readme = "README.md"
license = "Apache-2.0 OR MIT"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
clap = { version = "3.2.22", features = ["derive", "env", "wrap_help", "cargo"] }
clap-verbosity-flag = "1.0.1"
duct = "0.13.5"
env_logger = "0.9.1"
log = "0.4.17"
semver = "1.0.14"
tempfile = "3.3.0"
xshell = "0.2.2"
