[package]
name = "tool"
version = "0.1.0"
authors = ["Luke Hsiao <luke@hsiao.dev>"]
edition = "2021"
description = "A simple CLI tool my personal helper scripts."
repository = "https://github.com/lukehsiao/tool"
readme = "README.md"
license = "BlueOak-1.0.0"
categories = ["command-line-utilities"]
publish = false
rust-version = "1.64"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive", "env", "wrap_help", "cargo"] }
clap-verbosity-flag = "2.2.2"
duct = "0.13.7"
env_logger = "0.11.5"
log = "0.4.22"
once_cell = "1.19.0"
regex = "1.10.6"
semver = "1.0.23"
tempfile = "3.12.0"
tera = "1.19.1"
xshell = "0.2.6"
